PAIRS = [
    'BTCUSDT', 'ETHUSDT', 'ADAUSDT', 'LINKUSDT',
    'DOTUSDT', 'ATOMUSDT', 'LTCUSDT', 'MANAUSDT',
    'QTUMUSDT', 'XMRUSDT', 'BNBUSDT', 'XRPUSDT', 
    'SOLUSDT', 'MATICUSDT', 'UNIUSDT', 'AVAXUSDT',
    'XLMUSDT', 'ALGOUSDT', 'CAKEUSDT', 'RUNEUSDT'
]

TIMEFRAMES = ['1h', '4h', '1d']